// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache) Delete(key uuid.UUID) {
	_mock.Called(key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key uuid.UUID
func (_e *MockCache_Expecter) Delete(key any) *MockCache_Delete_Call {
	return &MockCache_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCache_Delete_Call) Run(run func(key uuid.UUID)) *MockCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call) Return() *MockCache_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call) RunAndReturn(run func(key uuid.UUID)) *MockCache_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(key uuid.UUID) (int64, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 int64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (int64, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) int64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key uuid.UUID
func (_e *MockCache_Expecter) Get(key any) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call) Run(run func(key uuid.UUID)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(n int64, b bool) *MockCache_Get_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(key uuid.UUID) (int64, bool)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockCache
func (_mock *MockCache) Put(key uuid.UUID, value int64) {
	_mock.Called(key, value)
	return
}

// MockCache_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockCache_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key uuid.UUID
//   - value int64
func (_e *MockCache_Expecter) Put(key any, value any) *MockCache_Put_Call {
	return &MockCache_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *MockCache_Put_Call) Run(run func(key uuid.UUID, value int64)) *MockCache_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Put_Call) Return() *MockCache_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Put_Call) RunAndReturn(run func(key uuid.UUID, value int64)) *MockCache_Put_Call {
	_c.Run(run)
	return _c
}
