// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockRepository
func (_mock *MockRepository) Deposit(ctx context.Context, id uuid.UUID, amount int64) (int64, error) {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (int64, error)); ok {
		return returnFunc(ctx, id, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) int64); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockRepository_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount int64
func (_e *MockRepository_Expecter) Deposit(ctx any, id any, amount any) *MockRepository_Deposit_Call {
	return &MockRepository_Deposit_Call{Call: _e.mock.On("Deposit", ctx, id, amount)}
}

func (_c *MockRepository_Deposit_Call) Run(run func(ctx context.Context, id uuid.UUID, amount int64)) *MockRepository_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Deposit_Call) Return(n int64, err error) *MockRepository_Deposit_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Deposit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, amount int64) (int64, error)) *MockRepository_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockRepository_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetBalance(ctx any, id any) *MockRepository_GetBalance_Call {
	return &MockRepository_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, id)}
}

func (_c *MockRepository_GetBalance_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetBalance_Call) Return(n int64, err error) *MockRepository_GetBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_GetBalance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (int64, error)) *MockRepository_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockRepository
func (_mock *MockRepository) Withdraw(ctx context.Context, id uuid.UUID, amount int64) (int64, error) {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (int64, error)); ok {
		return returnFunc(ctx, id, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) int64); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockRepository_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount int64
func (_e *MockRepository_Expecter) Withdraw(ctx any, id any, amount any) *MockRepository_Withdraw_Call {
	return &MockRepository_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, id, amount)}
}

func (_c *MockRepository_Withdraw_Call) Run(run func(ctx context.Context, id uuid.UUID, amount int64)) *MockRepository_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Withdraw_Call) Return(n int64, err error) *MockRepository_Withdraw_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Withdraw_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, amount int64) (int64, error)) *MockRepository_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache) Delete(key uuid.UUID) {
	_mock.Called(key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key uuid.UUID
func (_e *MockCache_Expecter) Delete(key any) *MockCache_Delete_Call {
	return &MockCache_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCache_Delete_Call) Run(run func(key uuid.UUID)) *MockCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call) Return() *MockCache_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call) RunAndReturn(run func(key uuid.UUID)) *MockCache_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(key uuid.UUID) (int64, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 int64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (int64, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) int64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key uuid.UUID
func (_e *MockCache_Expecter) Get(key any) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call) Run(run func(key uuid.UUID)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(n int64, b bool) *MockCache_Get_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(key uuid.UUID) (int64, bool)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockCache
func (_mock *MockCache) Put(key uuid.UUID, value int64) {
	_mock.Called(key, value)
	return
}

// MockCache_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockCache_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key uuid.UUID
//   - value int64
func (_e *MockCache_Expecter) Put(key any, value any) *MockCache_Put_Call {
	return &MockCache_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *MockCache_Put_Call) Run(run func(key uuid.UUID, value int64)) *MockCache_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Put_Call) Return() *MockCache_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Put_Call) RunAndReturn(run func(key uuid.UUID, value int64)) *MockCache_Put_Call {
	_c.Run(run)
	return _c
}
