// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Deposit(ctx context.Context, id uuid.UUID, amount int64) error {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockUseCase_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount int64
func (_e *MockUseCase_Expecter) Deposit(ctx any, id any, amount any) *MockUseCase_Deposit_Call {
	return &MockUseCase_Deposit_Call{Call: _e.mock.On("Deposit", ctx, id, amount)}
}

func (_c *MockUseCase_Deposit_Call) Run(run func(ctx context.Context, id uuid.UUID, amount int64)) *MockUseCase_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_Deposit_Call) Return(err error) *MockUseCase_Deposit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_Deposit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, amount int64) error) *MockUseCase_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockUseCase_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUseCase_Expecter) GetBalance(ctx any, id any) *MockUseCase_GetBalance_Call {
	return &MockUseCase_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, id)}
}

func (_c *MockUseCase_GetBalance_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUseCase_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetBalance_Call) Return(n int64, err error) *MockUseCase_GetBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUseCase_GetBalance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (int64, error)) *MockUseCase_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Withdraw(ctx context.Context, id uuid.UUID, amount int64) error {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockUseCase_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount int64
func (_e *MockUseCase_Expecter) Withdraw(ctx any, id any, amount any) *MockUseCase_Withdraw_Call {
	return &MockUseCase_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, id, amount)}
}

func (_c *MockUseCase_Withdraw_Call) Run(run func(ctx context.Context, id uuid.UUID, amount int64)) *MockUseCase_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_Withdraw_Call) Return(err error) *MockUseCase_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_Withdraw_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, amount int64) error) *MockUseCase_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
